# Site Information
site_name: AMD MI300X ML Benchmarks
site_description: Comprehensive benchmarking suite for AMD MI300X GPU performance analysis
site_author: Carlos Montemuiño
site_url: https://cmontemuino.github.io/amd-mi300x-ml-benchmarks/

# Repository Information
repo_name: cmontemuino/amd-mi300x-ml-benchmarks
repo_url: https://github.com/cmontemuino/amd-mi300x-ml-benchmarks
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Carlos Montemuiño

# Configuration
docs_dir: docs
site_dir: site

# Theme Configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - toc.integrate
    - header.autohide

# Navigation Structure
nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: getting-started/quick-start.md
      - Installation: getting-started/installation.md
      - Sample Data: getting-started/sample-data.md
  - User Guide:
      - Analysis Commands: user-guide/analysis-commands.md
      - Configuration: user-guide/configuration.md
      - Understanding Results: user-guide/analysis-guide.md
  - API Reference:
      - Overview: api/index.md
      - Core Analysis: api/analysis.md
      - Data Schemas: api/schemas.md
      - Utilities: api/utils.md
  - Development:
      - Contributing: CONTRIBUTING.md
      - Architecture: development/architecture.md
      - Testing: development/testing.md
  - Research:
      - Methodology: research/methodology.md
      - Citation: research/citation.md

# Markdown Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

  # PyMdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: cmontemuino
      repo: amd-mi300x-ml-benchmarks
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      timezone: Europe/Amsterdam
  - git-authors
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: table
            heading_level: 2
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: true
            show_root_toc_entry: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true

# Extra Configuration
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cmontemuino/amd-mi300x-ml-benchmarks
  version:
    provider: mike
    default: latest

# Extra JavaScript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extra CSS
extra_css:
  - stylesheets/extra.css